Documentation improved
starwit-trainings/react-simple_counter pull request #1
Opened 2024-01-24 10:10 UTC by Kaosfaktor

2024-01-24 14:11 UTC, flonix8 requested changes

2024-01-24 14:11 UTC, flonix8 commented on README.md
> +## Start a new Project in React, you need NodeJS and NPM
This goes for all section headings: 
I would keep them shorter and put the sentences into the section...

2024-01-24 14:11 UTC, flonix8 commented on README.md
> +Node.js is a Javascript runtime environment that processes data very quickly and is easy to scale. NPM is a Package Manager which is available for public use. NPM allows us to easily use code written
I would suggest less marketing but maybe some information on how to actually get `npm` installed, i.e. that you have to install `node` to get it. Mentioning that npm is a JavaScript package manager that is formally part of the `node` ecosystem should be enough.

2024-01-24 14:11 UTC, flonix8 commented on README.md
>  npx create-react-app simple-counter
create-react-app is sadly deprecated. This is why we had to remove it from all our frontends. If it is okay for a training repository is another question.

2024-01-24 14:11 UTC, flonix8 commented on README.md
> +### Start the application now with npm start (runs on localhost:3000), here we can view our result "on-the-fly".
Tell the user to point their browser at `localhost:3000`

2024-01-24 14:12 UTC, flonix8 commented
The elephant in the room is probably that `create-react-app` is deprecated and should not be used anymore. I have not looked yet if there is a somewhat easy to use replacement....

2024-01-25 08:31 UTC, witchpou reviewed
I would suggest to make a agenda/toc and chapters like:
* creating a react app
* build and dependency management
* creating a react component
* manage form input

2024-01-25 08:31 UTC, witchpou commented on README.md
> +Node.js is a Javascript runtime environment that processes data very quickly and is easy to scale. NPM is a Package Manager which is available for public use. NPM allows us to easily use code written
```suggestion
Node.js is a Javascript runtime environment that processes data very quickly and is easy to scale. NPM is a Package Manager which is available for public use (see https://www.npmjs.com/). Dependencies resolved via npm are listed in the package.json. The command `npm install` creates a folder `node-modules` in your project directory and downloads all dependencies.
```

2024-01-25 08:36 UTC, witchpou commented on README.md
> +The 'p' element defines a paragraph of text. Paragraphs are used to structure a text.
this is html and not relevant for react

2024-02-01 14:28 UTC, merged